### ISSUE TITLE
Which version? This one, or the fork?

### ISSUE THREAD

**Issue by richelbilderbeek** [mdfortune/simGWAS#7]
I see that both authors of the paper that describes simGWAS have their own repo, with this one being the primary one. The fork of the other, however, on https://github.com/chr1swallace/simGWAS appears to be more active: the fork had its last commit 6 months ago, this repo 36 months ago.

I suggest to remove this confusion. This can be done in many ways, which I leave up to the two authors.

For me, this is important, as I need to pick one GWAS simulation software from many. The state of a GitHub repo affects my decision.

Good luck and I would be happy to help!

**Comment by chr1swallace** [comment]
https://github.com/chr1swallace/simGWAS is the current version.

**Comment by richelbilderbeek** [comment]
Thanks!
